### ISSUE TITLE
feat(gitflow): add support for reverting merge commits on master

### ISSUE THREAD

**Issue by dmccaffery** [automotiveMastermind/condo#101]
Currently, some source control servers that enforce branch policies require a `--no-ff` merge to master, which impacts the ability to perform gitflow correctly.

The recommended solution is the following:

* when current branch is master
* when build is a server-side build (CI)
* when HEAD commit is a merge commit
* when merge commit has no diff to HEAD~1 commit
* when HEAD~1 contains ***NO_CI*** (versioned by condo)
* revert merge commit
* force push HEAD~1 commit as new HEAD

**Comment by sjk07** [comment]
is this something we still want to do? AFAIK this is only an issue in VSTS. Using a forking strategy will remove the need for such a feature.

**Comment by dmccaffery** [comment]
Agreed. We can close.
