### ISSUE TITLE
feat(npm): add support for installing NodeJS and NPM

### ISSUE THREAD

**Issue by dmccaffery** [automotiveMastermind/condo#102]
Condo should automatically install the NodeJS and NPM dependencies in the event that a package.json is detected.

* [ ] - install npm on windows
* [ ] - install npm on macos
* [ ] - install npm on linux

**Comment by dmccaffery** [comment]
This is likely a mute point once condo is dockerized.

**Comment by sjk07** [comment]
condo is now dockerized can be done inside container easily now
