### ISSUE TITLE
feat: write out environment variables to parent powershell session

### ISSUE THREAD

**Issue by bsambrone** [automotiveMastermind/condo#110]
Condo currently writes out msbuild environment variables within the powershell session that condo itself is executing. The calling powershell session does not have access to the environment variables scoped within Condo's session. Can either these environment variables be promoted to the caller's scope as well, or written out in a way so the calling session can access the data stored in these environment variables?

**Comment by dmccaffery** [comment]
This is blocked by the lack of `EnvironmentVariableTarget.{User,Machine}` API for `Environment.SetEnvironmentVariable` in .NET Standard 1.x. This API is being expanded for .NET Standard 2.0. I will keep an eye on the release of .NET Standard 2.0 and re-evalulate at that point in time.

In the meantime, I have added an API to allow the saving of arbitrary content to files on the file system from within Condo, which should unblock your requirements pending the availability of updated environment variable APIs.
