### ISSUE TITLE
feat(windows): Build using windows containers

### ISSUE THREAD

**Issue by sjk07** [automotiveMastermind/condo#126]
Break out from #83 
Currently there is no easy way to install a Git client on windows nanoserver. 

possible option is using Chocolaty but waiting on this issue to be resolved: 
https://github.com/chocolatey/choco/issues/1371

Any smart ideas here?
Will create a new Branch once #117 is merged in with current work.

**Comment by dmccaffery** [comment]
I'm fine not supporting windows containers. We can revisit this if and when it becomes an issue for someone, but as of now, there shouldn't be a need for windows builds. DocFX could be one issue; but I'm going to attempt to resolve by building on mono (again).

Closing for now.
