### ISSUE TITLE
fix(version): legacy sqlproj files will not version

### ISSUE THREAD

**Issue by bsambrone** [automotiveMastermind/condo#156]
At some point my CI build for a .sqlproj file started failing. Unknown when it started, but I do know it worked sometime in early November 2017. I don't want condo to build, since it can't build a legacy thing, but I DO want the version info and have it spit out a file. From running condo locally I can see the version info, but I don't see the output file that I used to see.

My current (sorta) working condo.build file that versions without the file:
`<Target Name="SetDacVersion">
	  <SaveFile RepositoryRoot="$(RepositoryRoot)" FilePath="version.txt" Content="$(RecommendedRelease)" />
    </Target>

	<PropertyGroup>
		<DotNetRestore>false</DotNetRestore>
		<DotNetBuild>false</DotNetBuild>
		<DotNetPack>false</DotNetPack>
		<DotNetTest>false</DotNetTest>
		<DotNetPublish>false</DotNetPublish>
	</PropertyGroup>
	
    <PropertyGroup>
        <AfterPublish>
            $(AfterPublish);
            SetDacVersion;
        </AfterPublish>
    </PropertyGroup>
	
	
	<Target Name="Initialize" />
  
	
	<Target Name="Version" DependsOnTargets="Initialize" />

  <Import Project="$(CondoTargetsPath)\Goals.targets" />
`

This was the version that was last working as of November and has since mysteriously broke:
`    </PropertyGroup>

    <Target Name="SetDacVersion">
	  <SaveFile RepositoryRoot="$(RepositoryRoot)" FilePath="version.txt" Content="$(RecommendedRelease)" />
    </Target>

	<PropertyGroup>
		<DotNetRestore>false</DotNetRestore>
		<DotNetBuild>false</DotNetBuild>
		<DotNetPack>false</DotNetPack>
		<DotNetTest>false</DotNetTest>
		<DotNetPublish>false</DotNetPublish>
	</PropertyGroup>
	
    <PropertyGroup>
        <AfterPublish>
            $(AfterPublish);
            SetDacVersion;
        </AfterPublish>
    </PropertyGroup>

  <Import Project="$(CondoTargetsPath)\Lifecycle.targets" />
  <Import Project="$(CondoTargetsPath)\Goals.targets" />
`

The original .build file that prompted me to make changes was throwing the below in the hosted VSTS agent:
`
"D:\a\1\s\condo.build" (Publish target) (1) ->
2018-01-03T23:01:23.1909181Z        (GetDotNetInfo target) -> 
2018-01-03T23:01:23.1910037Z          D:\a\1\s\src\am.database.ammdb\am.database.ammdb.sqlproj : error : InvalidProjectFileException: The imported project "C:\Users\buildguest\AppData\Local\Microsoft\dotnet\sdk\2.0.2\Microsoft\VisualStudio\v11.0\SSDT\Microsoft.Data.Tools.Schema.SqlTasks.targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.  D:\a\1\s\src\am.database.ammdb\am.database.ammdb.sqlproj [D:\a\1\s\condo.build]`

**Comment by dmccaffery** [comment]
@bsambrone looking into this

**Comment by sjk07** [comment]
Took a look at this and it seems like we changed something on when `AfterPublish` is called. Instead of using `AfterPublish` you can use `AfterVersion` and insert your new target there. ill close this since everything is working as expected.

```
    <PropertyGroup>
        <AfterVersion>
            $(AfterVersion);
            SetDacVersion;
        </AfterVersion>
    </PropertyGroup>
	
	<!-- initialize dynamic properties -->
	<Target Name="Initialize" />
  
	<!-- semantic versioning -->
	<Target Name="Version" DependsOnTargets="Initialize" />

    <!-- custom target to output text with version -->
    <Target Name="SetDacVersion" Condition="$(CI)">
	  <SaveFile RepositoryRoot="$(RepositoryRoot)" FilePath="version.txt" Content="$(RecommendedRelease)" />
    </Target>

  <Import Project="$(CondoTargetsPath)\Goals.targets" />
```
