### ISSUE TITLE
Add support for maintenance overviews

### ISSUE THREAD

**Issue by dmccaffery** [automotiveMastermind/condo#176]
http://isitmaintained.com

* [ ] - create project for is-maintained
* [ ] - add badges to readme

**Comment by sjk07** [comment]
do we actually create a project for is-maintained? or just use their hosted site to create the badges

**Comment by dmccaffery** [comment]
Might just be badges. They might analyze every GH project on the fly; not sure, honestly.

**Comment by sjk07** [comment]
Looks like it's just badges

[![Average time to resolve an issue](http://isitmaintained.com/badge/resolution/automotivemastermind/condo.svg)](http://isitmaintained.com/project/automotivemastermind/condo "Average time to resolve an issue")

[![Percentage of issues still open](http://isitmaintained.com/badge/open/automotivemastermind/condo.svg)](http://isitmaintained.com/project/automotivemastermind/condo "Percentage of issues still open")
