### ISSUE TITLE
Get E2E tests running in condo

### ISSUE THREAD

**Issue by jellyDean** [automotiveMastermind/condo#184]
Currently E2E test are not integrated into condo or VSTS. When engineers need to submit PRs all of the tests (including E2Es) must pass. Because the E2E tests are not ran it causes many issues. Currently members of the superfine team are required to take a screen shot of the E2E tests passing in VS CODE locally and paste it to the PR they working on. The goal of this task is to remove screenshooting and integrate E2E tests into condo and VSTS. The overall goal is broken into two parts. The first getting E2E tests running in condo and the second getting them running in VSTS. After getting the tests running in condo getting them in VSTS shouldn't be so bad.

Goals
- E2E tests passing without docker. Running condo.sh with all required dependencies running locally
- E2E tests passing with docker. Running condo.sh with all required dependencies in their own containers
- Integrating docker with condo. Condo spins up the necessary testing environment with all the required dependencies connected. Similar to VS Code task.
- Run condo and it spins up necessary testing environment and runs all tests including E2Es. Testing environment is destroyed upon test completion.

**Comment by sjk07** [comment]
Thanks for opening the issue! Can we get a description with the goals we would want to accomplish here? Can start through the discussion but should end up in the description of the issue

**Comment by dmccaffery** [comment]
Related to #49, if not identical

**Comment by dmccaffery** [comment]
Also re: VSTS, condo should remain as agnostic to build agent target as possible -- if utilizing #49 as the mechanism, then any platform that supports DinD should work out of the box. VSTS does not -- it uses DooD. Based on how the daemon is configured, it might "just work" regardless.

**Comment by sjk07** [comment]
this is a dup of #49 will move extra information from there to there.
