### ISSUE TITLE
Docker command failure, when project path contains space

### ISSUE THREAD

**Issue by kacperj** [automotiveMastermind/condo#215]
Please escape command parameters

Sample command from powershell run:
`docker build --label am.editorialcontent.api --tag am.editorialcontent.api:1.0.2-alpha-00166-1134 -f C:\Users\user\source\repos\New folder\com.example.proj1\src\Com.Example.Proj1\Dockerfile C:\Users\user\source\repos\New folder\com.example.proj1\src\Com.Example.Proj1`

**Comment by sjk07** [comment]
this should be solved by #216
