### ISSUE TITLE
GetRelease task does not support TGZ or GZ assets

### ISSUE THREAD

**Issue by dmccaffery** [automotiveMastermind/condo#238]

**Comment by dmccaffery** [comment]
In order to support the acquisition of `hugo` from the feed for platforms other than windows, we need to detect the file extension of the retrieved asset and extract TGZ or GZ when the extension is .tar.gz or .gz instead of attempting to extract a zip.

**Comment by dmccaffery** [comment]
... can use https://www.nuget.org/packages/SharpZipLib/ without requiring OS-level dependencies (until we switch our stack to GoLang :-))

**Comment by sjk07** [comment]
We will also need this for #242 so we can use normal compression types based on OS specific releases

**Comment by dmccaffery** [comment]
Closed by: #251
