### ISSUE TITLE
Issue encountered when attempting to push packages

### ISSUE THREAD

**Issue by Peter-Carr** [automotiveMastermind/condo#258]
Encountered this issue after repeatedly trying to get a service to build and deploy through Condo. Condo reports an issue with pushing packages to Azure which causes Condo to fail and not complete any more work after this step. After these failed Condo runs the new packages **DO** appear in Azure, but the docker image deployment to GCP and likely other steps after pushing packages are seemingly not executed.

Link to exact site of issue in AM Azure Devops [HERE](https://automotivemastermind.visualstudio.com/aM/_build/results?buildId=28394&view=logs&jobId=12f1170f-54f2-53f3-20dd-22fc7dff55f9&taskId=81272fff-8a00-56ef-4096-e1936dc992d3&lineStart=2825&lineEnd=2839&colStart=1&colEnd=86).

Error message content:
 >      
>      1>/root/.am/condo/Targets/Publish/Dotnet.targets(35,5): warning : NuGet push failed for package: /target/6/s/artifacts/packages/AM.Dealership.Client.1.13.2.nupkg after 1 attempts with 1 retries remaining. [/target/6/s/condo.build] 1>/root/.am/condo/Targets/Publish/Dotnet.targets(35,5): warning : NuGet push failed for package: /target/6/s/artifacts/packages/AM.Dealership.Client.AspNetCore.1.13.2.nupkg after 1 attempts with 1 retries remaining. [/target/6/s/condo.build]
     1>/root/.am/condo/Targets/Publish/Dotnet.targets(35,5): warning : NuGet push failed for package: /target/6/s/artifacts/packages/AM.Dealership.Abstractions.1.13.2.nupkg after 1 attempts with 1 retries remaining. [/target/6/s/condo.build]
     1>/root/.am/condo/Targets/Publish/Dotnet.targets(35,5): warning : NuGet push failed for package: /target/6/s/artifacts/packages/AM.Dealership.Client.AspNetCore.1.13.2.nupkg after 2 attempts with 0 retries remaining. [/target/6/s/condo.build]
     1>/root/.am/condo/Targets/Publish/Dotnet.targets(35,5): warning : NuGet push failed for package: /target/6/s/artifacts/packages/AM.Dealership.Abstractions.1.13.2.nupkg after 2 attempts with 0 retries remaining. [/target/6/s/condo.build]
     1>/root/.am/condo/Targets/Publish/Dotnet.targets(35,5): warning : NuGet push failed for package: /target/6/s/artifacts/packages/AM.Dealership.Client.1.13.2.nupkg after 2 attempts with 0 retries remaining. [/target/6/s/condo.build]
     1>/root/.am/condo/Targets/Publish/Dotnet.targets(35,5): error : Failed to push package: /target/6/s/artifacts/packages/AM.Dealership.Abstractions.1.13.2.nupkg after 2 attempts. [/target/6/s/condo.build]
     1>/root/.am/condo/Targets/Publish/Dotnet.targets(35,5): error : Response status code does not indicate success: 409 (Conflict - The feed already contains 'AM.Dealership.Abstractions 1.13.2'. (DevOps Activity ID: 7B72A2E7-A252-40CC-866A-A911F036C618)). [/target/6/s/condo.build]
     1>/root/.am/condo/Targets/Publish/Dotnet.targets(35,5): error : Failed to push package: /target/6/s/artifacts/packages/AM.Dealership.Client.AspNetCore.1.13.2.nupkg after 2 attempts. [/target/6/s/condo.build]
     1>/root/.am/condo/Targets/Publish/Dotnet.targets(35,5): error : Response status code does not indicate success: 409 (Conflict - The feed already contains 'AM.Dealership.Client.AspNetCore 1.13.2'. (DevOps Activity ID: B7514D16-BF16-4459-8A43-9D6CF63D44B3)). [/target/6/s/condo.build]
     1>/root/.am/condo/Targets/Publish/Dotnet.targets(35,5): error : Failed to push package: /target/6/s/artifacts/packages/AM.Dealership.Client.1.13.2.nupkg after 2 attempts. [/target/6/s/condo.build]
     1>/root/.am/condo/Targets/Publish/Dotnet.targets(35,5): error : Response status code does not indicate success: 409 (Conflict - The feed already contains 'AM.Dealership.Client 1.13.2'. (DevOps Activity ID: F9B2C9F6-D4EB-479D-B5DF-9C67791EB8F1)). [/target/6/s/condo.build]
     1>Done Building Project "/target/6/s/condo.build" (publish target(s)) -- FAILED.

**Comment by dmccaffery** [comment]
@sjk07 : has this issue been resolved in Azure DevOps?

@DrHamHawkins : current thinking is that the NuGet API in Azure DevOps was incorrectly responding with 409 (CONFLICT) instead of 201 (CREATED) for a period of time, which condo (accurately) interpreted as an error.

**Comment by sjk07** [comment]
yeah, looks like it was an issue with the azure nuget api. 

Resolved.

**Comment by dmccaffery** [comment]
This still seems to be an issue -- re-opening and investigating

**Comment by dmccaffery** [comment]
@sjk07 is this resolved? I don't have visibility anymore :feelsgood:

**Comment by dmccaffery** [comment]
Yoo-hoo!

**Comment by sjk07** [comment]
yeah, I have not seen this in a while again. will close
