### ISSUE TITLE
feat(publish): Specify what target framework to publish and/or publish all targeted frameworks

### ISSUE THREAD

**Issue by sjk07** [automotiveMastermind/condo#66]
My current project is targeting both `net461` and `netstandard1.5` when trying to publish with condo i get the following error: 
```
 "C:\Users\scott.AMM\projects\Business.DealCalculator\condo.build" (Publish target) (1) ->
       (DotNetPublish target) ->       

C:\Users\scott.AMM\AppData\Local\Microsoft\dotnet\sdk\1.0.1\Sdks\Microsoft.NET.Sdk\buildCrossTargeting\Microsoft.NET.Sdk.targets(31,5): error : The 'P
ublish' target is not supported without specifying a target framework. The current project targets multiple frameworks, please specify the framework for the pu
blished application. [C:\Users\scott.AMM\projects\Business.DealCalculator\src\Business.Domain\Business.Domain.csproj] [C:\Users\scott.AMM\projects\Business.Dea
lCalculator\condo.build]
         C:\Users\scott.AMM\.am\condo\.src\src\AM.Condo\Targets\Publish.targets(27,5): error MSB3073: The command "dotnet publish "Business.Domain.csproj" --ou
tput "C:\Users\scott.AMM\projects\Business.DealCalculator\artifacts\publish\\Business.Domain" --configuration "Debug" /p:Version=0.0.1-alpha-00107-1535 /p:Gene
rateAssemblyInfo=false" exited with code 1. [C:\Users\scott.AMM\projects\Business.DealCalculator\condo.build]
```

I don't see any elegant way except for looping over the target frameworks and publishing each with the `-f` flag. Im probably missing something magical... i hope

**Comment by dmccaffery** [comment]
condo currently makes the assumption that a published artifact is for a single framework -- is `Business.Domain` something that is actually published (console app, service, etc), or is it a library?

Can you share the top-level property group for that csproj? It likely shouldn't be called by the publish target at all.

**Comment by sjk07** [comment]
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>netstandard1.5;net461</TargetFrameworks>
    <!--<CodeAnalysisRuleSet>../../stylecop.ruleset</CodeAnalysisRuleSet>-->
  </PropertyGroup>

  <ItemGroup>
      <AdditionalFiles Include="../../stylecop.json" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MongoDB.Bson">
      <Version>2.4.3</Version>
    </PackageReference>
    <!--<PackageReference Include="StyleCop.Analyzers" Version="[1.0.0, 2.0.0)">
      <PrivateAssets>All</PrivateAssets>
    </PackageReference>-->
  </ItemGroup>

</Project>
```

It is a library, that should be referenced between other services. I have to do it this way currently since i need some type of abstraction between EF6 and .netcore stuff....

**Comment by dmccaffery** [comment]
@sjk07 looks fine to me -- condo is incorrectly detecting this project for publish -- unless a ```<Publish>true</Publish>``` or an ```<OutputType>Exe</OutputType>``` exists, it shouldn't be attempting to publish this particular project.

**Comment by dmccaffery** [comment]
@sjk07 please run condo using the following and let me know if this is resolved for you:

```posh
.\condo.ps1 -Reset -Branch bugfix/detect-pub /t:Publish
```

**Comment by sjk07** [comment]
Will check tonight on my desktop!
