### ISSUE TITLE
feat: dockerize condo

### ISSUE THREAD

**Issue by dmccaffery** [automotiveMastermind/condo#83]
add support for executing condo as a docker container:

- [x] derive a docker container from [microsoft/dotnet](https://store.docker.com/images/dotnet)/[latest](https://github.com/dotnet/dotnet-docker/blob/master/1.1/sdk/jessie/Dockerfile) (Linux)
- [x] derive a docker container from [microsoft/dotnet](https://store.docker.com/images/dotnet)/[nanoserver](https://github.com/dotnet/dotnet-docker/blob/master/1.1/sdk/nanoserver/Dockerfile) (Windows)
- [x] map /src within the container to $pwd
- [x] copy precompiled copy of condo tasks to /condo within the containers
- [x] create simplified condo init script for use within the container
  - [x] use well-known paths /condo and /src
  - [x] do NOT update condo within the container
  - [x] remove support for sourcing condo from different paths, uris, and branches
  - [x] do NOT install dotnet or the sdk within the container (will already exist)
  - [x] exec msbuild against /src/condo.build with the condo targets path set appropriately
- [x] update default condo.sh and condo.ps1 to execute condo within a container when available
  - [x] detect docker-cli
  - [x] pull and run latest condo container with mapped /src path
  - [x] pass cli arguments through to the condo init script within the container

**Comment by sjk07** [comment]
How involved is this? Would love to give it a shot

**Comment by dmccaffery** [comment]
I will update with tasks in this feature later tonight :)

**Comment by dmccaffery** [comment]
@sjk07 sorry for the delay -- I've added what I believe to be the required tasks to getting this working effectively. Feel free to put in multiple PR's as you work through this if you still want to take it up -- no need for an all or nothing approach.

**Comment by sjk07** [comment]
After chatting with @dmccaffery we have decided to go with the following:

- Create a docker image for each version of .net core (*unix and winodws)
- Pulled container will be specified via global.json. Default will be latest. Override specified by CLI flag

**Comment by sjk07** [comment]
#153 closes this
