### ISSUE TITLE
docs: update readme

### ISSUE THREAD

**Issue by dmccaffery** [automotiveMastermind/condo#84]
- [x] update the vitals to reflect the new builds (travis, appveyor, circle-ci)
- [x] update the gitter.im link
- [x] update the CREDITS
  - [x] add @sjk07 (contributor)
  - [x] add @brandon-a-hay (contributor)
  - [x] add @tiffanywang3 (contributor)
  - [x] add @falquan (reviewer)
  - [x] add @keith9820 (reviewer)
  - [x] add @juri-miyamoto (reviewer)
- [x] update "What is Condo" to reflect the current state
  - [x] remove npm, bower, gulp, and grunt support
  - [x] remove project.json support for condo >=2.0.0
  - [x] only dotnet tests are discovered and executed (remove protractor, mocha, etc)
  - [x] add docfx generation
    - [ ] reference prerequisites for docfx generation
      - [ ] windows
      - [ ] 2015 build tools (https://www.microsoft.com/en-us/download/details.aspx?id=48159) dotnet/docfx#1628
  - [x] add github-pages publishing
- [x] reference the `project-json` branch for backward support
  - [x] support for project.json will be dropped entirely with the launch of .net standard 2.0

**Comment by dmccaffery** [comment]
@sjk07 -- can we take care of this when we setup the docker example for aM welcome kit?

**Comment by sjk07** [comment]
@dmccaffery yup, we can def knock this out

**Comment by dmccaffery** [comment]
@tiffanywang3 want to take a crack at some of these?
